### ISSUE TITLE
PHP5 style constructors

### ISSUE THREAD

**Issue by kenjis** [thomas-ernest/CodeIgniter-for-PHP_CodeSniffer#10]
```
  11 | ERROR | PHP5 style constructors are not allowed; use "Blog" instead

  13 | ERROR | PHP5 style calls to parent constructors are not allowed. Please
     |       | use "parent::CI_Controller" instead.
```

These errors are for CI 1.x. 

In CI 2.x, `__construct()` and `parent::__construct()` are coding style.

**Comment by thomas-ernest** [comment]
Thanks for the return.

I'll try to fix that quickly, before the end of the next week.

**Comment by thomas-ernest** [comment]
Hi Kenjis,

Can you confirm me the fix this in commit 6755991 is working for you please ?

Thanks in advance.

**Comment by kenjis** [comment]
Thanks! It worked for me.

**Comment by thomas-ernest** [comment]
Cool :-)
