### ISSUE TITLE
Project application root

### ISSUE THREAD

**Issue by ianckc** [thomas-ernest/CodeIgniter-for-PHP_CodeSniffer#13]
After running the sniff I am left with one error which is 

 89 | ERROR | Unable to find "/application/" in file path "C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\mywebsite\application\controllers\main.php"
    |       | Please set your project's application root.

Is this to do with the closing comment at the end of main.php

// Location: ./application/controllers/main.php

I tried changing it to an absolute path of "C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\mywebsite\application\controllers\main.php" but this didn't fix it.

Any help on how to solve this would be great.

Thanks for making the sniff it's great.

**Comment by thomas-ernest** [comment]
Hi,

Sorry for the delay. My answer may be too late, but let's try quickly.
1/ You're right : it's about the location comment to close files. /!\ The position of the location comment and the file name comment is very important. I don't remember which one has to be first, but it will/must matter.
2/ It's useless to use the full path, everything is based on a property defined in ruleset.xml. Change the value in the ruleset.xml inside your PHP_CodeSniffer setup or you will have to run the ant build script every times for the change to propagate, if you edit it in the ruleset.xml in source.

``` xml
<rule ref="CodeIgniter.Files.ClosingLocationComment">
    <properties>
      <!-- End of the path pointing to your project's application root or all of it. -->
      <property name="applicationRoot" value="/application/"/>
    </properties>
  </rule>
```

As far as I recall, the sniff checks that the file in My_path_to_CI/application/my_directory/file.php contains a location comment with path application/my_directory/file.php or my_directory/file.php only, if the property is /application/ or My_path_to_CI/application/.

Hope That help though it's very approximate

**Comment by ianckc** [comment]
Thanks for the answer.

I'll have a look into it and let you know how it goes.
