### ISSUE TITLE
Undefined variable in ValidVariableNameSniff.php

### ISSUE THREAD

**Issue by jacksonj04** [thomas-ernest/CodeIgniter-for-PHP_CodeSniffer#14]
The variable `scopeSpecified` in `Sniffs/NamingConventions/ValidVariableNameSniff.php` on line 205 doesn't seem to be used anywhere else, and it's not immediately clear what it's used for or where it would be set. As a result a PHP Notice is thrown.

**Comment by thomas-ernest** [comment]
I merged your change. So, I mean I can close this issue. Feel free to open it again.

Thanks for your help.
