### ISSUE TITLE
Codeigniter Control Structures

### ISSUE THREAD

**Issue by ghost** [thomas-ernest/CodeIgniter-for-PHP_CodeSniffer#16]
This is a great standard but are there any plans to do ControlStructures Sniffs?

eg to ensure that it's done like this

```
if (...)
{
}
```

rather than

```
if(...) {
}
```

**Comment by thomas-ernest** [comment]
I haven't had time to release or re-use sniffs to test Allman style indenting. It might be already developed for another coding standard using PHP_CodeSniffers, but I couldn't find it back in time.

Feel free to open a pull request or to give me the name of sniffs (or the coding standard supported by PHP_CodeSniffers) ensuring this coding style.
