### ISSUE TITLE
Function comment

### ISSUE THREAD

**Issue by Lechus** [thomas-ernest/CodeIgniter-for-PHP_CodeSniffer#19]
Hi,
For:
        /**
         \* Dekoder  - wyswietla informacje o produkcje - dekoderze
         \* 
         \* @access public
         \* @param string $ktory Model Dekodera do wyswietlenia
         \* @return string www
         */
        public function dekoder($ktory='ferguson_ariva100') 

I get:

125 | ERROR | Last parameter comment requires a blank newline after it
125 | ERROR | Parameters must appear immediately after the comment

Why? It is from: http://codeigniter.com/user_guide/general/styleguide.html#commenting

**Comment by thomas-ernest** [comment]
Hi,

May you try with that and tell me if you've got the same errors please :
/**
         \* Dekoder  - wyswietla informacje o produkcje - dekoderze
         \* 
         \* @param string $ktory Model Dekodera do wyswietlenia
         \* 
         \* @return string www
         \* 
         \* @access public
         */

**Comment by Lechus** [comment]
Hi,
There are no errors now.
But why it needs new line?

**Comment by thomas-ernest** [comment]
It requires new lines because I have reused some existing sniffs requiring new lines.

It doesn't match the example in CodeIgniter style guide  - the link above -, but it provides a basic check.
