### ISSUE TITLE
Fix class-file name problem comes from Squiz

### ISSUE THREAD

**Issue by deadtrickster** [thomas-ernest/CodeIgniter-for-PHP_CodeSniffer#2]
By CI standard class names should start with first upcase letter. Squiz.Classes.ClassFileName emits an error when you have class Test in file test.php.

**Comment by thomas-ernest** [comment]
Squiz_Sniffs_Classes_ClassFileNameSniff has been replaced with CodeIgniter_Sniffs_NamingConventions_ValidFileNameSniff. It should make the deal. Can you said, if it is ok ?
