### ISSUE TITLE
Use of And over &&

### ISSUE THREAD

**Issue by gantir** [thomas-ernest/CodeIgniter-for-PHP_CodeSniffer#21]
Dear Thomas,

Both as per Codeigniter standards and also as per the php behavior using && is preferred to AND.
Can you please update the code to reflect this:
&& is preferred over AND
AND / OR over and / or.

Currently you consider using && as error which should not be the case.

Reference Links: 
[Codeigniter](http://codeigniter.com/user_guide/general/styleguide.html#logical_operators)
[And vs &&](http://stackoverflow.com/questions/2803321/and-vs-as-operator)

**Comment by thomas-ernest** [comment]
Hello Ramjee,

I fixed this issue about logical operators AND, &&, OR and ||.
Could you review it before I close it please ?

Thanks in advance,
Thomas.

P.S : I also added a sniff about else and elseif control structures. It ensures they stand on a new line, as it is shown in one of examples in [Code indenting](http://codeigniter.com/user_guide/general/styleguide.html#code_indenting) of CodeIgniter style guide. It would be great, if you could check it in the same time.

**Comment by gantir** [comment]
Hi Thomas,

We never got to check if this issue was fixed.  Just today we checked it and it looks like it is  fixed.
Thanks a lot for the fix.
