### ISSUE TITLE
PHP Fatal error:  Interface 'PHP_CodeSniffer_Sniff' not found

### ISSUE THREAD

**Issue by rkorebrits** [thomas-ernest/CodeIgniter-for-PHP_CodeSniffer#25]
When I try to run `phpcs` (both from CLI and PhpStorm), I get the following error(s)

`D:\Projects\ditto>phpcs` --standard=CodeIgniter www\index.php
PHP Fatal error:  Interface 'PHP_CodeSniffer_Sniff' not found in C:\xampp\php\PHP\CodeSniffer\Standards\CodeIgniter\Sniffs\Commenting\InlineCommentSniff.php on line 28`

I'm running on PHPCS 3.0.0RC1

What could the issue be? Is this version not supported?

**Comment by mehdibo** [comment]
This sniffer is old, I've been looking for a valid one since yesterday but no luck

**Comment by rkorebrits** [comment]
I had no luck in the end. Let me know if you find something :-)

**Comment by mehdibo** [comment]
I didn't find any, I tried making my own but it's not perfect: https://github.com/mehdibo/CodeIgniter-PHP_CodeSniffer

**Comment by ganl** [comment]
Try this in PHP_CodeSniffer 3.x :  https://github.com/ganl/CodeIgniter-for-PHP_CodeSniffer @rkorebrits

**Comment by rkorebrits** [comment]
Thanks @ganl Seems to work fine! Only my code seems to be quite off :-(
