### ISSUE TITLE
syntax error unexpected T_VARIABLE

### ISSUE THREAD

**Issue by jusurb** [thomas-ernest/CodeIgniter-for-PHP_CodeSniffer#4]
PHP Parse error:  syntax error, unexpected T_VARIABLE in /usr/share/php/PHP/CodeSniffer/Standards/CodeIgniter/Sniffs/NamingConventions/ValidFileNameSniff.php on line 62

i believe the following line:
$fileName = substr($fileNameAndExt, 0, strrpos(f$ileNameAndExt, '.'));

should be:
$fileName = substr($fileNameAndExt, 0, strrpos($fileNameAndExt, '.'));

**Comment by thomas-ernest** [comment]
Thank you.
It must be fixed with commit 41caee6799abc890c93e8147964bc06bfdc25337 [1].
Cheers.

[1] https://github.com/thomas-ernest/CodeIgniter-for-PHP_CodeSniffer/commit/41caee6799abc890c93e8147964bc06bfdc25337
