### ISSUE TITLE
calling private method from parent class

### ISSUE THREAD

**Issue by jusurb** [thomas-ernest/CodeIgniter-for-PHP_CodeSniffer#5]
PHP Fatal error:  Call to private method CodeIgniter_Sniffs_Files_AbstractClosingCommentSniff::_getCommentContent() from context 'CodeIgniter_Sniffs_Files_ClosingFileCommentSniff' in /usr/share/php/PHP/CodeSniffer/Standards/CodeIgniter/Sniffs/Files/ClosingFileCommentSniff.php on line 89

maybe _getCommentContent() should be protected?
`protected static function _getCommentContent ($comment)`

**Comment by thomas-ernest** [comment]
Hi Gamesh.

Thanks for pointing out these bugs and providing fixes.

I set _getCommentContent($comment) and _stringStartWith($haystack, $needle) from private to protected with commit 4fa21890d50ca366c69efcd3eddb88061822fb2b [1].
I cannot check that now. So, if it's ok for you please close the issue.

I'll take a look at Issue #6 in next day (or maybe tonight).

Cheers.

[1] https://github.com/thomas-ernest/CodeIgniter-for-PHP_CodeSniffer/commit/4fa21890d50ca366c69efcd3eddb88061822fb2b

**Comment by jusurb** [comment]
looks goods and works ok :)
