### ISSUE TITLE
endless loop

### ISSUE THREAD

**Issue by jusurb** [thomas-ernest/CodeIgniter-for-PHP_CodeSniffer#6]
while checking core's Benchmark class i encountered a endless loop somewhere in CodeIgniter_Sniffs_NamingConventions_ValidVariableNameSniff

cmd used:
`phpcs --standard=CodeIgniter -vvv -l Benchmark.php`

verbose log:
http://pastebin.com/dkDv8ncX

**Comment by thomas-ernest** [comment]
Hi Gamesh,

Could you give me the file you used to run into an endless loop (as you did for the log) please ?

Thanks in advance

**Comment by jusurb** [comment]
i don't see how to attach file here, so i put it in the pastebin:

http://pastebin.com/TFMLigim

**Comment by thomas-ernest** [comment]
Thank you for providing the file Benchmark.php.

I guess I fixed the bug with commit ab8c6b4.
Please keep telling me, if you see other wrong behaviors.

**Comment by thomas-ernest** [comment]
Feel free to reopen this issue, if I'm wrong.
