### ISSUE TITLE
Class Name case

### ISSUE THREAD

**Issue by francisco-baptista** [thomas-ernest/CodeIgniter-for-PHP_CodeSniffer#7]
My class is

  class Groups extends MY_Controller
  {

After running phpcs --standard=codeigniter -n groups.php 

I get:

  ERROR | Class names should always have their first letter uppercase. Multiple words should be separated with an underscore, and not CamelCased. Please consider Ggroups instead of Groups

Regards

**Comment by francisco-baptista** [comment]
not the most elegant solution but 

  Sniffs/NamingConventions/ValidClassNameSniff.php

  $expectedClassName = strtoupper($className[0]) . strtolower(substr($lcClassNameChunk, 1));

this fixes it.

#regexpurefear

regards

**Comment by thomas-ernest** [comment]
Thank you for sharing this solution with me :)

I've just pushed it into the repository. I forgot a "as suggested by francisco-baptista" in the commit message, sorry.
Could you check my fix again and close the issue, if it works for you please.

I've also found another little error that is already fixed about the insertion of underscore in front of uppercase letters ;)

Regards
