### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by fukata** [thomas-ernest/CodeIgniter-for-PHP_CodeSniffer#8]
Hi,

After execute the "segmentation fault" was phpcs.

Sniffs/Files/Utf8EncodingSniff.php#_checkUtf8W3c segmentation fault occurs when you check the application/config/config.php on CodeIgniter 2.0.2.
### /var/log/messages

```
Aug  7 18:21:48 ci kernel: [ 1404.374216] phpcs[1517]: segfault at 7ffff42bbf7c ip 00007faa3973ba52 sp 00007ffff42bbf20 error 6 in libpcre.so.3.12.1[7faa3972b000+2d000]
```

**Comment by kenjis** [comment]
I have got the same error:

$ phpcs -v --standard=CodeIgniter --encoding=utf-8 config.php 
Registering sniffs in CodeIgniter standard... DONE (32 sniffs registered)
Creating file list... DONE (1 files in queue)
Processing config.php [775 tokens in 362 lines]... Segmentation fault

**Comment by mukthar** [comment]
Most probably  this issue is due to large number of strings passed to an internal function for checking UTF. I am trying to upload a patch which worked for me.
